# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_bsbanners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='bannertype',
            field=models.SmallIntegerField(choices=[(1, 'Carousel'), (2, 'Jumbotron'), (3, 'Image')], default=1),
        ),
    ]
