# Generated by Django 2.0.13 on 2019-02-28 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_bsbanners', '0002_auto_20161102_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='carouseltransition',
            field=models.CharField(choices=[('slide', 'Slide'), ('fade', 'Fade')], default='slide', help_text='Animate slides with a slide or fade transition.', max_length=5, verbose_name='Carousel transition'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='slug',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slides',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='slides', verbose_name='Image'),
        ),
    ]
